AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'config/**/*.rb'

Metrics/BlockLength:
    IgnoredMethods: ['describe', 'context']
Style/Documentation:
  Enabled: false
MethodLength:
  Max: 20
